plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/ExtraSpacing:
  Exclude:
    - 'lib/generators/cmdx/templates/install.rb'
Layout/LineLength:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'spec/**/**/*'
Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/cmdx/coercions/**/*'
    - 'lib/cmdx/validators/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'lib/cmdx/rspec/**/*'
    - 'spec/**/**/*'
    - '*.gemspec'
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/integrations/**/*'
RSpec/ExampleLength:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/SpecFilePathFormat:
  CustomTransform:
    CMDx: cmdx
RSpec/StubbedMock:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/VerifiedDoubleReference:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  SafeAutoCorrect: true
Style/ModuleFunction:
  EnforcedStyle: extend_self
Style/OpenStructUse:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantException:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
