plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/LineLength:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'spec/**/**/*'
Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/cmdx/coercions/**/*'
    - 'lib/cmdx/middlewares/**/*'
    - 'lib/cmdx/log_formatters/**/*'
    - 'lib/cmdx/validators/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/integrations/**/*'
RSpec/ExampleLength:
  Enabled: false
RSpec/SpecFilePathFormat:
  CustomTransform:
    CMDx: cmdx
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  SafeAutoCorrect: true
Style/ModuleFunction:
  EnforcedStyle: extend_self
Style/OptionalBooleanParameter:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
