plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.1
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'spec/**/**/*'
Lint/ShadowedException:
  Enabled: false
Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/cmdx/coercions/**/*'
    - 'lib/cmdx/log_formatters/**/*'
    - 'lib/cmdx/middlewares/**/*'
    - 'lib/cmdx/validators/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/integrations/**/*'
RSpec/ExampleLength:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/SpecFilePathFormat:
  CustomTransform:
    CMDx: cmdx
RSpec/SubjectStub:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/VerifiedDoubleReference:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  SafeAutoCorrect: true
Style/ModuleFunction:
  EnforcedStyle: extend_self
Style/OptionalBooleanParameter:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
